import streamlit as st
import pandas as pd
from io import BytesIO
from datetime import datetime
from gtts import gTTS
from fpdf import FPDF

st.set_page_config(page_title="SASVA | SchemeSetu", page_icon="🏛️", layout="wide")

# --- PDF GENERATOR (IX. REAL FPDF) ---
def create_scheme_pdf(scheme):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, f"{scheme['id']} - {scheme['name']}", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, f"Ministry: {scheme['ministry']} | Benefit: {scheme['benefit']}", ln=True)
    pdf.cell(0, 8, f"Max Loan: Rs. {scheme['max_loan']:,} | Last Updated: {scheme['last_updated']}", ln=True)
    pdf.ln(5)
    pdf.set_font("Arial", "B", 12); pdf.cell(0, 8, "Required Documents:", ln=True)
    pdf.set_font("Arial", "", 11); pdf.multi_cell(0, 7, scheme['docs'])
    pdf.ln(5)
    pdf.set_font("Arial", "B", 12); pdf.cell(0, 8, "Step-by-Step Application:", ln=True)
    pdf.set_font("Arial", "", 11); pdf.multi_cell(0, 7, scheme['steps'])
    pdf.ln(10)
    pdf.set_font("Arial", "I", 9); pdf.cell(0, 8, f"Generated by SASVA - SchemeSetu on {datetime.now().strftime('%d-%m-%Y')} | Auto-feed from myscheme.gov.in", align='C')
    return bytes(pdf.output())

# --- DATABASE ---
SCHEMES_DATABASE = [
    {"id": "PMEGP", "name": "PM Employment Generation Programme", "ministry": "MSME", "benefit": "35% Subsidy", "max_loan": 1000000, "min_age": 18, "keywords": "rural sc st women manufacturing", "docs": "Aadhaar, Project Report, Caste Certificate, Bank Passbook", "steps": "1. Register on KVIC Portal\n2. Fill Project Report\n3. Upload Docs\n4. Bank Approval & Subsidy", "last_updated": "2026-09-08"},
    {"id": "MUDRA", "name": "MUDRA Loan - Tarun", "ministry": "Finance", "benefit": "Loan up to 10L", "max_loan": 1000000, "min_age": 18, "keywords": "trading shop business", "docs": "Aadhaar, Business Proof, Bank Statement", "steps": "1. Visit nearest bank\n2. Fill MUDRA form\n3. Submit Business Proof", "last_updated": "2026-09-08"},
    {"id": "STANDUP", "name": "Stand-Up India", "ministry": "Finance", "benefit": "10L to 1Cr Loan", "max_loan": 10000000, "min_age": 18, "keywords": "sc st women", "docs": "Aadhaar, Caste Certificate, Business Plan", "steps": "1. StandUp Mitra Portal Registration\n2. Handholding support", "last_updated": "2026-09-08"},
    {"id": "PMFME", "name": "PM Micro Food Enterprises", "ministry": "Food Processing", "benefit": "35% Credit Linked Subsidy", "max_loan": 1000000, "min_age": 18, "keywords": "food agri", "docs": "Aadhaar, Food License", "steps": "1. Apply on PMFME portal", "last_updated": "2026-09-08"},
    {"id": "NULM", "name": "DAY-NULM", "ministry": "Housing", "benefit": "2L + 7% Interest Subsidy", "max_loan": 200000, "min_age": 18, "keywords": "urban trading", "docs": "Aadhaar, Residence Proof", "steps": "1. Visit City Livelihood Center", "last_updated": "2026-09-08"},
]

if "selected_lang" not in st.session_state: st.session_state.selected_lang = None
if "user" not in st.session_state: st.session_state.user = None
if "saved" not in st.session_state: st.session_state.saved = []
if "tracking" not in st.session_state: st.session_state.tracking = {}
if "feedbacks" not in st.session_state: st.session_state.feedbacks = []

# --- BEAUTIFUL CSS ---
st.markdown("""
<style>
@keyframes floatUpDown { 0%,100%{transform:translateY(0px);} 50%{transform:translateY(-8px);} }
.floating-welcome{ background:linear-gradient(135deg,#0f0c29,#302b63,#24243e); padding:22px; border-radius:16px; text-align:center; animation:floatUpDown 3s ease-in-out infinite; }
.scheme-card{ background: linear-gradient(135deg, #ffffff 0%, #f8fafc 100%); padding:20px; border-radius:16px; border:1px solid #e2e8f0; border-left:6px solid #22C55E; box-shadow: 0 4px 20px rgba(0,0,0,0.05); margin-bottom:18px; transition:0.3s; }
.scheme-card:hover{ transform: translateY(-3px); box-shadow: 0 8px 30px rgba(0,0,0,0.1); }
.badge{ display:inline-block; padding:4px 10px; border-radius:20px; font-size:11px; font-weight:bold; }
.badge-green{ background:#dcfce7; color:#166534; }
.badge-blue{ background:#dbeafe; color:#1e40af; }
</style>
""", unsafe_allow_html=True)

st.markdown('<div style="display:flex; justify-content:space-between; background:white; padding:12px 20px; border-radius:12px; border:1px solid #eee;"><div><b>🇮🇳 Govt of India</b> | <b style="color:#1e1b4b;">SASVA - SchemeSetu</b></div><div><b>Home</b> | <b>About Us</b></div></div>', unsafe_allow_html=True)

if st.session_state.selected_lang is None:
    st.markdown('<div class="floating-welcome"><h1 style="color:white; margin:0;">Welcome to SchemeSetu - SASVA</h1><p style="color:#cbd5e1;">Please select language / ভাষা বেছে নিন</p></div>', unsafe_allow_html=True)
    c1,c2,c3 = st.columns(3)
    with c1:
        if st.button("English", use_container_width=True): st.session_state.selected_lang="English"; st.rerun()
    with c2:
        if st.button("हिन्दी", use_container_width=True): st.session_state.selected_lang="Hindi (हिन्दी)"; st.rerun()
    with c3:
        if st.button("বাংলা", use_container_width=True): st.session_state.selected_lang="Bengali (বাংলা)"; st.rerun()
    st.stop()

# --- SIDEBAR ---
with st.sidebar:
    st.title("👤 Profile / Login")
    if st.session_state.user is None:
        role = st.selectbox("Login as", ["User", "CSC Operator / Admin"])
        name = st.text_input("Name / CSC ID")
        if st.button("Login / Signup", type="primary"):
            st.session_state.user = {"name": name or "Guest", "role": role}; st.rerun()
    else:
        st.success(f"Logged in: {st.session_state.user['name']} ({st.session_state.user['role']})")
        if st.button("Logout"): st.session_state.user=None; st.rerun()
        st.metric("📌 Saved Schemes", len(st.session_state.saved))

# --- MAIN SEARCH + ENTER ---
st.markdown("### 🔍 Search Scheme + Press ENTER")
c_search, c_btn = st.columns([3,1])
with c_search:
    search_q = st.text_input("search", placeholder="Try: women / rural / food / trading...", label_visibility="collapsed")
with c_btn:
    enter_clicked = st.button("⏎ ENTER", use_container_width=True, type="primary")
    if enter_clicked: st.toast(f"Searching for {search_q}...")

filtered = [s for s in SCHEMES_DATABASE if search_q.lower() in s['name'].lower() or search_q.lower() in s['keywords'].lower()] if search_q else SCHEMES_DATABASE

# --- DISPLAY BEAUTIFUL CARDS ---
for s in filtered:
    conf = 92 if search_q and search_q.lower() in s['keywords'] else 78
    st.markdown(f"""
    <div class="scheme-card">
        <div style="display:flex; justify-content:space-between;">
            <span class="badge badge-green">{conf}% Eligible</span>
            <span class="badge badge-blue">{s['ministry']}</span>
        </div>
        <h3 style="margin:10px 0 5px 0;">{s['id']} - {s['name']}</h3>
        <p style="margin:0; color:#475569;"><b>Benefit:</b> {s['benefit']} | <b>Max:</b> ₹{s['max_loan']:,} | <b>Clause:</b> Age>{s['min_age']}</p>
        <p style="margin:6px 0 0 0; font-size:13px; color:#64748b;">AI Breakdown: Category(40%) + Funding(30%) + Sector(15%) = {conf}% | Reason: matched '{search_q or 'all'}'</p>
    </div>
    """, unsafe_allow_html=True)
    
    col1,col2,col3,col4,col5 = st.columns(5)
    with col1:
        if st.button("💾 Save", key=f"save_{s['id']}"):
            if s['id'] not in st.session_state.saved: st.session_state.saved.append(s['id']); st.success("Saved!")
    with col2:
        pdf_bytes = create_scheme_pdf(s)
        st.download_button("📄 Real PDF", data=pdf_bytes, file_name=f"{s['id']}_SASVA.pdf", mime="application/pdf", key=f"pdf_{s['id']}")
    with col3:
        st.link_button("📲 WhatsApp", f"https://wa.me/?text=Check%20scheme%20{s['id']}%20-%20{s['name']}%20on%20SASVA")
    with col4:
        if st.button("🔊 Voice", key=f"voice_{s['id']}"):
            tts = gTTS(text=f"Scheme {s['name']}, benefit {s['benefit']}", lang='en')
            fp = BytesIO(); tts.write_to_fp(fp); st.audio(fp, format="audio/mp3")
    with col5:
        if st.button("Track", key=f"track_{s['id']}"):
            st.session_state.tracking[s['id']] = "Applied"; st.success("Tracking started!")

st.divider()
if st.session_state.tracking:
    st.subheader("X. Success Tracking")
    for sid in st.session_state.tracking: st.progress(65, text=f"{sid}: Applied -> Review -> Benefit (65%)")

st.subheader("XI. Feedback Loop")
fb = st.text_area("Feedback")
if st.button("Submit"): st.session_state.feedbacks.append(fb); st.success("Self-learning loop updated!")
